version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: memfs
    versions:
    - 3.2.1
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: mocha
    versions:
    - 8.3.2
  - dependency-name: chai
    versions:
    - 4.3.1
    - 4.3.4
  - dependency-name: graceful-fs
    versions:
    - 4.2.5
